# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_facade.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../00_facade.ipynb 3
def say_hello(to:str):
    "Say hello to somebody"
    return f'Hello {to}!'
